### PR TITLE
Adds flag for disabling parent zone record creation + context.tf upgrade

### PR DESCRIPTION
**Pull request by Gowiem**
## what
* Adds `var.parent_zone_record_enabled` flag for the ability to disable creating the record on the parent zone. 
* Adds context.tf pattern 

## why
* This can be used to support the parent zone being in a different account and creating this record outside of this module.

### CODE REVIEW

**Review by jamengual — DISMISSED** [review]

**Comment by jamengual** [comment]
@Gowiem can you rebase?

**Comment by Gowiem** [comment]
@jamengual Done! Thanks for the bump.

**Review by jamengual — APPROVED** [review]

**Pull request merged**
